/**
 * @pharmaet/contracts — the single source of truth for the client/server contract (ADR-010).
 *
 * Every type here is authored once, as a Zod schema, and consumed three ways:
 *   - TypeScript types, by the API and the dashboard, via `z.infer`;
 *   - runtime validation at the API boundary, by the same schema;
 *   - Dart classes in apps/mobile/lib/contracts/, generated by `pnpm gen:contracts`.
 *
 * Hand-writing either side of this contract is what docs/05-qa §6 exists to forbid: a
 * client and server that disagree about the envelope do not fail loudly, they silently lose
 * or duplicate real transactions.
 */
export * from './version.js';
export * from './primitives.js';
export * from './entities.js';
export * from './sync.js';
export * from './auth.js';
// The FR-2 permission matrix. Here rather than in the API because AC-2.1 requires the
// denial at both the app and the API layer, and two copies of a permission table drift.
export * from './permissions.js';
// Gregorian <-> Ethiopian conversion and its cross-language test vectors (FR-10, BR-10.2).
// Here so the console and the till cannot disagree about what day it is.
export * from './ethiopian-calendar.js';
