import { Column, CreateDateColumn, PrimaryColumn, UpdateDateColumn, VersionColumn } from 'typeorm';
import { bigintTransformer } from '../common/transformers/numeric.transformer';

/**
 * Columns every synced table carries (docs/04-system-design.md §2).
 *
 * `id` is NOT generated by the database. The client mints a UUIDv7 offline and the server
 * honours it (ADR-006) — that is what makes an offline write complete before it has ever
 * reached us, and what makes a replayed push idempotent.
 */
export abstract class SyncedEntity {
  @PrimaryColumn('uuid')
  id: string;

  @Column('uuid', { name: 'tenant_id' })
  tenantId: string;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;

  /** Soft-delete marker. Nothing in this system is ever physically deleted (NFR-5.3). */
  @Column('timestamptz', { name: 'deleted_at', nullable: true })
  deletedAt: Date | null;

  /** Optimistic concurrency; compared against an operation's `baseVersion` on update. */
  @VersionColumn({ name: 'row_version' })
  rowVersion: number;

  /**
   * Server-assigned per-tenant monotonic cursor driving delta pull (docs/04 §7.2).
   * Deliberately not `updated_at`: offline terminals have skewed clocks, and equal
   * timestamps tie, which loses rows at a page boundary.
   */
  @Column('bigint', { name: 'change_seq', default: 0, transformer: bigintTransformer })
  changeSeq: number;
}
